// 分销商模块

//  分销商状态
export const DEALERS_AUDIT_STATE = {
  NO_CHECK: 1, // 待审核
  SUCCESS_CHECK: 2, // 审核通过
  FAIL_CHECK: 3, // 审核失败
};
export const DEALERS_AUDIT_STATE_TEXT = {
  [DEALERS_AUDIT_STATE.NO_CHECK]: "待审核",
  [DEALERS_AUDIT_STATE.SUCCESS_CHECK]: "审核通过",
  [DEALERS_AUDIT_STATE.FAIL_CHECK]: "审核失败",
};
// 审核options
export const DEALERS_AUDIT_STATE_OPTIONS = () => [
  {
    label: DEALERS_AUDIT_STATE_TEXT[DEALERS_AUDIT_STATE.NO_CHECK],
    value: DEALERS_AUDIT_STATE.NO_CHECK,
  },
  {
    label: DEALERS_AUDIT_STATE_TEXT[DEALERS_AUDIT_STATE.SUCCESS_CHECK],
    value: DEALERS_AUDIT_STATE.SUCCESS_CHECK,
  },
  {
    label: DEALERS_AUDIT_STATE_TEXT[DEALERS_AUDIT_STATE.FAIL_CHECK],
    value: DEALERS_AUDIT_STATE.FAIL_CHECK,
  },
];

//  分销商订单状态
export const DEALERS_ORDER_STATE = {
  TO_BE_SETTLED: 1, // 待结算
  FINISH: 2, // 已完成
  CANCEL: 3, // 已关闭
};
export const DEALERS_ORDER_STATE_TEXT = {
  [DEALERS_ORDER_STATE.TO_BE_SETTLED]: "待结算",
  [DEALERS_ORDER_STATE.FINISH]: "已完成",
  [DEALERS_ORDER_STATE.CANCEL]: "已关闭",
};
// options
export const DEALERS_ORDER_STATE_OPTIONS = () => [
  {
    label: DEALERS_ORDER_STATE_TEXT[DEALERS_ORDER_STATE.TO_BE_SETTLED],
    value: DEALERS_ORDER_STATE.TO_BE_SETTLED,
  },
  {
    label: DEALERS_ORDER_STATE_TEXT[DEALERS_ORDER_STATE.FINISH],
    value: DEALERS_ORDER_STATE.FINISH,
  },
  {
    label: DEALERS_ORDER_STATE_TEXT[DEALERS_ORDER_STATE.CANCEL],
    value: DEALERS_ORDER_STATE.CANCEL,
  },
];
