// 分销商模块

//  分销商状态
export const DEALERS_AUDIT_STATE = {
  NO_CHECK: 1, // 待审核
  SUCCESS_CHECK: 2, // 审核通过
  FAIL_CHECK: 3, // 审核失败
};
export const DEALERS_AUDIT_STATE_TEXT = {
  [DEALERS_AUDIT_STATE.NO_CHECK]: "待审核",
  [DEALERS_AUDIT_STATE.SUCCESS_CHECK]: "审核通过",
  [DEALERS_AUDIT_STATE.FAIL_CHECK]: "审核失败",
};
// 审核options
export const DEALERS_AUDIT_STATE_OPTIONS = () => [
  {
    label: DEALERS_AUDIT_STATE_TEXT[DEALERS_AUDIT_STATE.NO_CHECK],
    value: DEALERS_AUDIT_STATE.NO_CHECK,
  },
  {
    label: DEALERS_AUDIT_STATE_TEXT[DEALERS_AUDIT_STATE.SUCCESS_CHECK],
    value: DEALERS_AUDIT_STATE.SUCCESS_CHECK,
  },
  {
    label: DEALERS_AUDIT_STATE_TEXT[DEALERS_AUDIT_STATE.FAIL_CHECK],
    value: DEALERS_AUDIT_STATE.FAIL_CHECK,
  },
];
