// 积分设置模块

// 奖励积分
export const REWARD_INTEGRAL_STATE = {
  GIVE: 1, // 赠送
  NOT_GIFTED: 2, // 不赠送
};
export const REWARD_INTEGRAL_STATE_TEXT = {
  [REWARD_INTEGRAL_STATE.GIVE]: "赠送",
  [REWARD_INTEGRAL_STATE.NOT_GIFTED]: "不赠送",
};
export const REWARD_INTEGRAL_STATE_OPTIONS = () => [
  {
    label: REWARD_INTEGRAL_STATE_TEXT[REWARD_INTEGRAL_STATE.GIVE],
    value: REWARD_INTEGRAL_STATE.GIVE,
  },
  {
    label: REWARD_INTEGRAL_STATE_TEXT[REWARD_INTEGRAL_STATE.NOT_GIFTED],
    value: REWARD_INTEGRAL_STATE.NOT_GIFTED,
  },
];

// 商品类型
export const APPLY_PRODUCT_TYPE = {
  ALL: 1, // 全部商品
  PART: 2, // 部分商品
};
export const APPLY_PRODUCT_TYPE_TEXT = {
  [APPLY_PRODUCT_TYPE.ALL]: "全部商品",
  [APPLY_PRODUCT_TYPE.PART]: "部分商品",
};

// 服务点类型
export const SERVE_TYPE = {
  ALL: 1, // 全部服务点
  PART: 2, // 部分服务点
};
export const SERVE_TYPE_TEXT = {
  [APPLY_PRODUCT_TYPE.ALL]: "全部服务点",
  [APPLY_PRODUCT_TYPE.PART]: "部分服务点)",
};

// 活动限制日期类型
export const ACTIVITY_LIMIT_DATE_TYPE = {
  LONG_ACTIVITY: 1, // 长期活动
  LIMITED_TIME: 2, // 限期活动
};
export const ACTIVITY_LIMIT_DATE_TYPE_TEXT = {
  [ACTIVITY_LIMIT_DATE_TYPE.LONG_ACTIVITY]: "长期活动",
  [ACTIVITY_LIMIT_DATE_TYPE.LIMITED_TIME]: "限期活动",
};
export const ACTIVITY_LIMIT_DATE_TYPE_OPTIONS = () => [
  {
    label:
      ACTIVITY_LIMIT_DATE_TYPE_TEXT[ACTIVITY_LIMIT_DATE_TYPE.LONG_ACTIVITY],
    value: ACTIVITY_LIMIT_DATE_TYPE.LONG_ACTIVITY,
  },
  {
    label: ACTIVITY_LIMIT_DATE_TYPE_TEXT[ACTIVITY_LIMIT_DATE_TYPE.LIMITED_TIME],
    value: ACTIVITY_LIMIT_DATE_TYPE.LIMITED_TIME,
  },
];

// 积分瓜分活动类型
export const INTEGRAL_CARVE_ACTIVITY_TYPE = {
  LONG_TERM: 1, // 长期活动
  LIMITED_TIME: 2, // 期限活动
};

export const ACTIVITY_TYPE_TEXT = {
  [INTEGRAL_CARVE_ACTIVITY_TYPE.LONG_TERM]: "长期活动",
  [INTEGRAL_CARVE_ACTIVITY_TYPE.LIMITED_TIME]: "期限活动",
};

export const ACTIVITY_TYPE_OPTIONS = () => [
  {
    label: ACTIVITY_TYPE_TEXT[INTEGRAL_CARVE_ACTIVITY_TYPE.LONG_TERM],
    value: INTEGRAL_CARVE_ACTIVITY_TYPE.LONG_TERM,
  },
  {
    label: ACTIVITY_TYPE_TEXT[INTEGRAL_CARVE_ACTIVITY_TYPE.LIMITED_TIME],
    value: INTEGRAL_CARVE_ACTIVITY_TYPE.LIMITED_TIME,
  },
];
